### PR TITLE
Trigger tagbot, not cron

### PR DESCRIPTION
**Pull request by Libbum**
The #pkg-registration peeps are highlighting just how many requests this is causing. So best we update.

### CODE REVIEW

**Comment by Datseris** [comment]
Can you explain to me what this is doing and whether I should also put it to other packages of JuliaDynamics like DynamicalSystems or Agents?

**Comment by Libbum** [comment]
Yep, so it's already in Agents, and you should do it for all the other packages you run. 

Basically, the previous version of the Tagbot structure set up a timer and just pinged JuliaRegistries continuously to check if there was something to do. This ended up with over 300,000 requests an hour or something stupid. 

New version only invokes the script when Tagbot comments in #18. Advantage is that the script is run straight away rather than waiting for the cron timer, and JuliaRegistries isn't hammered.

**Comment by Datseris** [comment]
@kahaaga you should add this to CausalityTools and co. as well

**Comment by Datseris** [comment]
I guess this would be a good time to learn how to use Julia to make massive PRs to different repos, but I'm too lazy.

**Comment by kahaaga** [comment]
@Libbum Thanks for notifying about this! 

> you should add this to CausalityTools and co. as well

I'm on it.

> I guess this would be a good time to learn how to use Julia to make massive PRs to different repos, but I'm too lazy.

I share that sentiment :D

**Pull request merged**
