### PR TITLE
[Help needed] `FixedMassABM` does not work

### PR DESCRIPTION
**Pull request by Datseris**
I am trying to update the code here so that the new model types in Agents.jl v5.7 are possible to use. But `FixedMassABM` does not work. I am getting a rather difficult to interpret error about some conversion that is nested deeply in `SizedVector`. The problem is: I am anyways making anything a normal `Vector` before the `lift` is applied. So I can't understand what is the problem.

To reproduce error: ensure you have Agents.jl v5.7 and then run the `examples/agents/agents_flocking.jl` example, which I've updated to `FixedMassABM`.

### CODE REVIEW

**Comment by Datseris** [comment]
Error: if you use CairoMakie, you get this error:
```
Display Error: ERROR: MethodError: Cannot `convert` an object of type Point{2, Float32} to an object of type Float32
Closest candidates are:
  convert(::Type{T}, ::ColorTypes.Gray24) where T<:Real at C:\Users\gd419\.julia\packages\ColorTypes\1dGw6\src\conversions.jl:114
  convert(::Type{T}, ::ColorTypes.Gray) where T<:Real at C:\Users\gd419\.julia\packages\ColorTypes\1dGw6\src\conversions.jl:113
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273

Stacktrace:
  [1] macro expansion
    @ C:\Users\gd419\.julia\packages\StaticArraysCore\U2Z1K\src\StaticArraysCore.jl:81 [inlined]
  [2] convert_ntuple
    @ C:\Users\gd419\.julia\packages\StaticArraysCore\U2Z1K\src\StaticArraysCore.jl:77 [inlined]
  [3] Vec{3, Float32}(x::Tuple{Point{2, Float32}, Point{2, Float32}, Point{2, Float32}})
    @ GeometryBasics C:\Users\gd419\.julia\packages\GeometryBasics\KE3OI\src\fixed_arrays.jl:19
  [4] to_ndim(T::Type{Vec{3, Float32}}, vec::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}, fillval::Float32)
    @ Makie C:\Users\gd419\.julia\packages\Makie\gAmAB\src\utilities\utilities.jl:232
  [5] _project_position(scene::Scene, space::Symbol, point::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}, model::StaticArraysCore.SMatrix{4, 4, Float32, 16}, yflip::Bool)
    @ CairoMakie C:\Users\gd419\.julia\packages\CairoMakie\CX6Wo\src\utils.jl:13
  [6] project_position(scene::Scene, transform_func::Tuple{typeof(identity), typeof(identity)}, space::Symbol, point::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}, model::StaticArraysCore.SMatrix{4, 4, Float32, 16}, yflip::Bool)
    @ CairoMakie C:\Users\gd419\.julia\packages\CairoMakie\CX6Wo\src\utils.jl:8
  [7] project_position(scene::Scene, transform_func::Tuple{typeof(identity), typeof(identity)}, space::Symbol, point::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}, model::StaticArraysCore.SMatrix{4, 4, Float32, 16})
    @ CairoMakie C:\Users\gd419\.julia\packages\CairoMakie\CX6Wo\src\utils.jl:7
  [8] (::CairoMakie.var"#31#32"{Scene, Cairo.CairoContext, Tuple{typeof(identity), typeof(identity)}, StaticArraysCore.SMatrix{4, 4, Float32, 16}, StaticArraysCore.SMatrix{4, 4, Float32, 16}, FreeTypeAbstraction.FTFont, 
Symbol, Symbol})(point::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}, col::ColorTypes.RGBA{Float32}, markersize::Int64, strokecolor::ColorTypes.RGBA{Float32}, strokewidth::Float32, m::StaticArraysCore.SizedVector{100, BezierPath, Vector{BezierPath}}, mo::Vec{2, Float32}, rotation::Quaternionf) 
    @ CairoMakie C:\Users\gd419\.julia\packages\CairoMakie\CX6Wo\src\primitives.jl:212
  [9] macro expansion
    @ C:\Users\gd419\.julia\packages\Makie\gAmAB\src\utilities\utilities.jl:202 [inlined]
 [10] broadcast_foreach(::CairoMakie.var"#31#32"{Scene, Cairo.CairoContext, Tuple{typeof(identity), typeof(identity)}, StaticArraysCore.SMatrix{4, 4, Float32, 16}, StaticArraysCore.SMatrix{4, 4, Float32, 16}, FreeTypeAbstraction.FTFont, Symbol, Symbol}, ::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}, ::ColorTypes.RGBA{Float32}, ::Int64, ::ColorTypes.RGBA{Float32}, ::Float32, ::StaticArraysCore.SizedVector{100, BezierPath, Vector{BezierPath}}, ::Vec{2, Float32}, ::Quaternionf)
    @ Makie C:\Users\gd419\.julia\packages\Makie\gAmAB\src\utilities\utilities.jl:188
 [11] draw_atomic_scatter(scene::Scene, ctx::Cairo.CairoContext, transfunc::Tuple{typeof(identity), typeof(identity)}, colors::ColorTypes.RGBA{Float32}, markersize::Int64, strokecolor::ColorTypes.RGBA{Float32}, strokewidth::Float32, marker::StaticArraysCore.SizedVector{100, BezierPath, Vector{BezierPath}}, marker_offset::Vec{2, 
Float32}, rotations::Quaternionf, model::StaticArraysCore.SMatrix{4, 4, Float32, 16}, positions::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}, size_model::StaticArraysCore.SMatrix{4, 4, Float32, 16}, font::FreeTypeAbstraction.FTFont, markerspace::Symbol, space::Symbol)
    @ CairoMakie C:\Users\gd419\.julia\packages\CairoMakie\CX6Wo\src\primitives.jl:205
 [12] draw_atomic(scene::Scene, screen::

...
```


If you use GLMakie you get a different error, which is:

```
Display Error: ERROR: Object Point{2, Float32} is not a supported uniform element type
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] opengl_prefix(T::Type)
    @ GLMakie.GLAbstraction C:\Users\gd419\.julia\packages\GLMakie\N16Fq\src\GLAbstraction\GLUniforms.jl:13   
  [3] glsl_typename(t::Type{StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}}) 
    @ GLMakie.GLAbstraction C:\Users\gd419\.julia\packages\GLMakie\N16Fq\src\GLAbstraction\GLUniforms.jl:97   
  [4] glsl_typename(x::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}})       
    @ GLMakie.GLAbstraction C:\Users\gd419\.julia\packages\GLMakie\N16Fq\src\GLAbstraction\GLUniforms.jl:90   
  [5] toglsltype_string(x::StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}})
    @ GLMakie.GLAbstraction C:\Users\gd419\.julia\packages\GLMakie\N16Fq\src\GLAbstraction\GLUniforms.jl:111  
  [6] toglsltype_string(t::Observable{StaticArraysCore.SizedVector{100, Point{2, Float32}, Vector{Point{2, Float32}}}})
    @ GLMakie.GLAbstraction C:\Users\gd419\.julia\packages\GLMakie\N16Fq\src\GLAbstraction\GLUniforms.jl:110  
  [7] mustache2replacement(mustache_key::String, view::Dict{String, String}, attributes::Dict{Symbol, Any})   
    @ GLMakie.GLAbstraction C:\Users\gd419\.julia\packages\GLMakie\N16Fq\src\GLAbstraction\GLShader.jl:337    
  [8] gl_convert(cache::GLMakie.GLAbstraction.ShaderCache, lazyshader::GLMakie.GLVisualizeShader, data::Dict{Symbol, Any})
    @ GLMakie.GLAbstraction C:\Users\gd419\.julia\packages\GLMakie\N16Fq\src\GLAbstraction\GLShader.jl:250    
  [9] gl_convert

...
```

**Comment by Datseris** [comment]
I truly have no idea how to resolve this :( :( :( :( :(

**Comment by Datseris** [comment]
@SimonDanisch I know it is impossible for you to go into the source here. It is too complicated. But are you by chance aware of any complications that may arise when trying to plot a `SizedVector{Point2f}` instead of a normal `Vector{Point2}`...?

**Comment by SergeyNovak777** [comment]
Hello, is this problem still relevant? I faced a similar problem with CairoMake.
Are you have 32 bit windows or 64?
If you have 64-bit Windows, try converting your data to Float64. I think it's worth trying to convert the Point{2, Float32} to Float32 yourself

**Pull request closed without merging**
