### PR TITLE
Add docs section about custom plots

### PR DESCRIPTION
**Pull request by fbanning**
This docs section is added in response to https://github.com/JuliaDynamics/Agents.jl/issues/551.

@Datseris I would like to add two screenshots to this section. Where would you normally store those? I saw that you've stored the videos for the docs landing page on the JuliaDynamics github space.

### CODE REVIEW

**Comment by Datseris** [comment]
Hi @fbanning cool! Yeap we store "external" images here https://github.com/JuliaDynamics/JuliaDynamics/tree/master/videos/agents  in order to minimize download size!

**Comment by fbanning** [comment]
I don't need to bum the patch number for a docs update, right?

**Comment by Datseris** [comment]
for the change to be reflected in the stable docs yes. However at the moment `master` branch is unstable because graph space uses Graphs.jl and OSM uses LightGraphs.jl. So don't bother with bversions!

**Comment by fbanning** [comment]
> at the moment `master` branch is unstable

You might be thinking about Agents right now. As far as I can tell, InteractiveDynamics does not have anything specifically unstable in its current master branch. If you're OK with my additions in this PR, I would say you could already merge it.

**Comment by Datseris** [comment]
It is getting really hard to keep track of many large projects.... :D

**Pull request merged**
