### PR TITLE
(NOT WORKING) Add heatmap for Continuous Spaces

### PR DESCRIPTION
**Pull request by franfram**
Hi George, 
This is what I've done to add the heatmap for continuous spaces but it doesn't work. Could you give me some advise/guidance on how to do it properly?

Cheers, 
Fran

### CODE REVIEW

**Comment by Datseris** [comment]
Hi @franfram , when something doesn't work be very precise about it. What doesn't work, what is the exact error message, and what would you expect to have happened. I see here you call heatmap twice, once with limits and once without. Shouldn't you instead have an `else` clause that then plots the heatmap without limits, instead? What is currently happening if you run the code?

**Comment by franfram** [comment]
Hello George, 
I've been trying to improve my workflow for deving the package. I'm currently using Revise.jl but I don't seem to be able to use it properly with InteractiveDynamics. 
Particularly, I'm making some changes to /src/agents/lifting.jl in order to understand how to package works, but I don't seem to be able to use the recently modified version. 

These are the things that  I'm doing: 
A)
1. Get a dev version of InteractiveDynamics using `Pkg.dev("InteractiveDynamics")`
2. Go to the dev folder of InteractiveDynamics, make some changes to lifting.jl and save them. 
3. Restart the Julia session
4. Run the ABM code that I have for continuous spaces to see the changes in the abmplot() function. 
These steps don't seem to work, mainly because I cannot see the changes that I make in lifting.jl. For example, I change the error message in the function definition of `abmplot_heatobs()` inside lifting.jl but then I don't get the updated error message when calling abmplot() in my ABM code. 

B) Using Revise.jl
1. Get a dev version of InteractiveDynamics using `Pkg.dev("InteractiveDynamics")`
2. Make Revise.jl track the file I'm about to change by using `include()` or `includet()`. For example, `include("/home/user/.julia/dev/InteractiveDynamics/src/agents/lifting.jl")`
3. Make some changes to the file
4. run Revise.revise()
The problem here is that when I do 2., I get errors like: 
```
julia> Revise.include("src/agents/lifting.jl")
ERROR: LoadError: UndefVarError: @lift not defined
in expression starting at /home/arnle/.julia/dev/InteractiveDynamics/src/agents/lifting.jl:6

julia> Revise.include("src/agents/abmplot.jl")
ERROR: LoadError: UndefVarError: Observable not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/dev/InteractiveDynamics/src/agents/model_observable.jl:3
in expression starting at /home/arnle/.julia/dev/InteractiveDynamics/src/agents/model_observable.jl:3
```

I made some stackoverflow questions and asked on julia's slack, but I don't seem to get it right. 
Could you guide me on how you dev InteractiveDynamics properly?
PD: I can send you a video of what I'm doing if you want.

**Comment by franfram** [comment]
Now workflow A) works properly, not sure why. Nvm
Hopefully in a few days I have something to show you with respect to InteractiveDynamics. 

Cheers!

**Comment by franfram** [comment]
Hello @Datseris 
I've been diving into the InteractiveDynamics codebase (made a ton of stackoverflow/slack/discourse questions and learned a lot. )
Now I'm kinda stuck again. Mainly, can't figure out where to get the `abmplot.heatarray` argument of the `lift_attributes` function (I want to get that argument to test a few things inside the `abmplot_heatobs` function)
I really want to do the PR but I've started falling behind in my PhD assignments. Would you like to do a 10min meeting so that I can show you what I'm doing with InteractiveDynamics and get some advise/guidance?

Cheers!

**Comment by Datseris** [comment]
Hi! Yes, I can advise you in a meeting. The only time I can make it is tomorrow (Sunday) if you are available. I am fully booked in the next week, as odd as it sounds. If you don't have time tomorrow, it is okay. I will fix the PR if I have time, as I am giving a workshop on Agents.jl on Friday!

**Comment by franfram** [comment]
Tomorrow is fine for me. What time do you prefer?

**Comment by Datseris** [comment]
I'll send a mail once I am home, some time after 2-3 oclock. After I'm home I'll be available all the time.

**Comment by franfram** [comment]
Great

**Pull request merged**
